# Generated by Django 6.0.4 on 2026-04-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="e.g., 'pintxos', 'sbk'", unique=True)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(help_text="e.g., 'pintxos.maps.eus'", max_length=255)),
                ('primary_color', models.CharField(default='#f97316', help_text='Hex color', max_length=7)),
                ('secondary_color', models.CharField(default='#84cc16', max_length=7)),
                ('font_family', models.CharField(default="'Inter', sans-serif", max_length=100)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='app_branding/')),
                ('has_reviews', models.BooleanField(default=True)),
                ('has_maps', models.BooleanField(default=True)),
                ('has_bookings', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'App Registries',
            },
        ),
    ]
