# Generated by Django 6.0.5 on 2026-05-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscription',
            new_name='core_subscr_user_id_d435c1_idx',
            old_name='core_subscr_user_status_idx',
        ),
    ]
