# Generated by Django 6.0.5 on 2026-05-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0008_rename_core_subscr_user_status_idx_core_subscr_user_id_d435c1_idx",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appregistry",
            options={
                "ordering": ["display_priority", "name"],
                "verbose_name_plural": "App Registries",
            },
        ),
        migrations.AddField(
            model_name="appregistry",
            name="display_priority",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=100,
                help_text="Landing sort order (0 = first). Use multiples of 10 to leave room between apps.",
            ),
        ),
        migrations.AddField(
            model_name="appregistry",
            name="launch_status",
            field=models.CharField(
                choices=[
                    ("live", "Live"),
                    ("beta", "Beta"),
                    ("coming_soon", "Coming soon"),
                    ("archived", "Archived"),
                ],
                default="live",
                help_text="Drives landing badges and filtering (replaces is_featured as lifecycle signal).",
                max_length=16,
            ),
        ),
    ]
