# Generated by Django 6.0.4 on 2026-04-26 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(help_text='e.g., Dancer, DJ, Singer', max_length=100)),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goandance_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('festival', 'Festival / Congress'), ('party', 'Party / Social'), ('workshop', 'Workshop / Bootcamp')], default='festival', max_length=50)),
                ('primary_style', models.CharField(choices=[('salsa', 'Salsa'), ('bachata', 'Bachata'), ('kizomba', 'Kizomba'), ('urbankiz', 'Urban Kiz'), ('zouk', 'Zouk'), ('mixed', 'SBK / Mixed')], default='mixed', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ticket_url', models.URLField(blank=True, max_length=500, null=True)),
                ('estimated_pass_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artists', models.ManyToManyField(blank=True, related_name='events', to='sbk.artist')),
            ],
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('floor_quality', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1: Slippery/Sticky, 5: Perfect wood')),
                ('ac_ventilation', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1: Sauna, 5: Perfect AC')),
                ('gender_ratio', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1: Bad balance, 5: Perfect 50/50')),
                ('music_quality', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sbk.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('going', 'Going'), ('went', 'Went (Past)')], default='interested', max_length=50)),
                ('looking_for_roommate', models.BooleanField(default=False)),
                ('looking_for_dance_partner', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, help_text="E.g., 'Have a spare bed in my Airbnb'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbk.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbk_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
