# Generated by Django 6.0.5 on 2026-05-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbk', '0009_seed_load_events_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
