# Generated by Django 6.0.5 on 2026-05-10 11:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbk', '0010_event_ticket_clicks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(default='Euskadi', max_length=100)),
                ('venue_type', models.CharField(choices=[('academy', 'Academy'), ('social', 'Social room'), ('bar', 'Bar with dance night'), ('multi', 'Multi-purpose')], default='multi', max_length=20)),
                ('styles', models.JSONField(blank=True, default=list, help_text='List of style codes: salsa, bachata, kizomba, ...')),
                ('weekly_schedule', models.JSONField(blank=True, default=dict, help_text='Free-form: e.g. {"mon":{"class":["bachata-19h"]},"wed":{"social":["21h-2h"]}}')),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('avg_rating', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, help_text='Verified owner. Set when a DanceVenueClaim is approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_dance_venues', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dance_venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DanceVenueClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=16)),
                ('method', models.CharField(choices=[('phone', 'Phone call'), ('email', 'Domain email'), ('document', 'Document upload'), ('other', 'Other')], default='phone', max_length=16)),
                ('evidence', models.TextField(blank=True, help_text='Free-text proof: role, contact details, supporting info.')),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes left by the reviewer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbk_claims', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dance_venue_claims', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='sbk.dancevenue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenueRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.IntegerField()),
                ('floor_quality', models.IntegerField(blank=True, help_text='1: slippery/sticky, 5: perfect', null=True)),
                ('music_quality', models.IntegerField(blank=True, null=True)),
                ('crowd_level', models.IntegerField(blank=True, help_text='1: empty, 5: packed', null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dance_venue_ratings', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='sbk.dancevenue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dancevenue',
            index=models.Index(fields=['city', 'venue_type'], name='sbk_danceve_city_24227f_idx'),
        ),
        migrations.AddIndex(
            model_name='dancevenueclaim',
            index=models.Index(fields=['status', '-created_at'], name='sbk_danceve_status_6ff70e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dancevenueclaim',
            constraint=models.UniqueConstraint(fields=('venue', 'claimant'), name='uniq_dance_venue_claimant'),
        ),
        migrations.AlterUniqueTogether(
            name='venuerating',
            unique_together={('venue', 'user')},
        ),
    ]
