# Generated by Django 6.0.5 on 2026-05-10 18:41

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbk', '0011_dancevenue_dancevenueclaim_venuerating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='instagram_handle',
            new_name='instagram',
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sbk/people/'),
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('dj', 'DJ'), ('teacher', 'Teacher'), ('organizer', 'Organizer'), ('dancer', 'Dancer'), ('videographer', 'Videographer')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='person',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('override_venue', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.CharField(blank=True, help_text='iCalendar RRULE', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoccurrence',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='sbk.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='djs',
            field=models.ManyToManyField(blank=True, related_name='dj_events', to='sbk.person'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='sbk.person'),
        ),
        migrations.AddField(
            model_name='event',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teaching_events', to='sbk.person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='performing_events', to='sbk.person'),
        ),
        migrations.AddIndex(
            model_name='eventoccurrence',
            index=models.Index(fields=['event', 'start_date'], name='sbk_eventoc_event_i_1b8a2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventoccurrence',
            constraint=models.UniqueConstraint(fields=('event', 'start_date'), name='uniq_occurrence'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
    ]
