# Generated by Django 6.0.5 on 2026-05-12 19:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbk', '0013_alter_person_city_alter_person_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='artistic_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='styles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('salsa', 'Salsa'), ('bachata', 'Bachata'), ('kizomba', 'Kizomba'), ('urbankiz', 'Urban Kiz'), ('zouk', 'Zouk'), ('mixed', 'SBK / Mixed')], max_length=20), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='person',
            name='tiktok',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(blank=True, default='Spain', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', help_text='Full display name (auto-generated if empty)', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('dj', 'DJ'), ('teacher', 'Teacher'), ('organizer', 'Organizer'), ('dancer', 'Dancer'), ('videographer', 'Videographer'), ('promoter', 'Promoter')], max_length=20), blank=True, default=list),
        ),
    ]
