# Generated by Django 6.0.5 on 2026-05-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mubil", "0005_vehicle_idae_schema"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vehicle",
            name="vehicle_make_model_variant_year_unique",
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idae_id__isnull", True)),
                fields=("make", "model", "variant", "year"),
                name="vehicle_manual_natural_unique",
            ),
        ),
    ]
