# Generated by Django 6.0.5 on 2026-05-31 19:29

from django.db import migrations, models


def mark_existing_prices_as_mock(apps, schema_editor):
    """Las 41 filas seed con price_eur previo a v2 se marcan 'mock'.

    Razón: el seed manual original fue placeholder para que el advisor demo
    no devolviera payback None. La pipeline nueva (manual → heurística →
    Gemini) tratará 'mock' como sobrescribible mientras respeta 'manual'.
    """
    Vehicle = apps.get_model("mubil", "Vehicle")
    Vehicle.objects.filter(price_eur__isnull=False).update(price_source="mock")


def noop(apps, schema_editor):
    """Revertir es no-op: los datos viven en price_source, no hay info que perder."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("mubil", "0010_seed_demand_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="price_source",
            field=models.CharField(
                choices=[
                    ("unknown", "Desconocido"),
                    ("mock", "Mock (placeholder)"),
                    ("manual", "Verificado manual"),
                    ("heuristic", "Estimado heurístico"),
                    ("gemini", "Estimado Gemini"),
                ],
                db_index=True,
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="price_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_prices_as_mock, reverse_code=noop),
    ]
