# Generated by Django 6.0.4 on 2026-04-26 20:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(help_text='ID from the Euskadi API', max_length=255, unique=True, verbose_name='ID Origen')),
                ('title_es', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título (ES)')),
                ('title_eu', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título (EU)')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Descripción (ES)')),
                ('description_eu', models.TextField(blank=True, null=True, verbose_name='Descripción (EU)')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('venue_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Lugar')),
                ('municipality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipio')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='Provincia')),
                ('url_es', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL (ES)')),
                ('url_eu', models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL (EU)')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Imagen')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento Cultural',
                'verbose_name_plural': 'Eventos Culturales',
                'ordering': ['start_date'],
            },
        ),
    ]
