# Generated by Django 6.0.4 on 2026-04-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kultur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo/Categoría'),
        ),
    ]
