# Generated by Django 6.0.4 on 2026-05-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kultur', '0002_culturalevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalevent',
            name='event_type',
        ),
        migrations.AddField(
            model_name='culturalevent',
            name='event_type_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo/Categoría (ES)'),
        ),
        migrations.AddField(
            model_name='culturalevent',
            name='event_type_eu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo/Categoría (EU)'),
        ),
    ]
