# Generated by Django 6.0.5 on 2026-05-09 15:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kultur', '0006_index_event_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.CharField(max_length=500, verbose_name='Nombre (ES)')),
                ('name_eu', models.CharField(blank=True, default='', max_length=500, verbose_name='Nombre (EU)')),
                ('municipality', models.CharField(db_index=True, max_length=255, verbose_name='Municipio')),
                ('province', models.CharField(blank=True, default='', max_length=255, verbose_name='Provincia')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Ubicación')),
                ('geocoding_source', models.CharField(default='municipality_centroid', max_length=32, verbose_name='Origen geocoding')),
                ('geocoded_at', models.DateTimeField(blank=True, null=True, verbose_name='Geocodificado en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'constraints': [models.UniqueConstraint(fields=('name_es', 'municipality'), name='uniq_venue_name_municipality')],
            },
        ),
        migrations.AddField(
            model_name='culturalevent',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='kultur.venue', verbose_name='Lugar'),
        ),
    ]
