# Generated by Django 6.0.5 on 2026-05-10 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kultur', '0008_populate_venues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KulturPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_categories', models.JSONField(blank=True, default=list)),
                ('default_moods', models.JSONField(blank=True, default=list)),
                ('default_municipality', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kultur_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencias kultur',
                'verbose_name_plural': 'Preferencias kultur',
            },
        ),
        migrations.CreateModel(
            name='EventFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='kultur.culturalevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kultur_favs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento favorito',
                'verbose_name_plural': 'Eventos favoritos',
                'indexes': [models.Index(fields=['user', '-created_at'], name='kultur_even_user_id_076148_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'event'), name='uniq_user_event_fav')],
            },
        ),
    ]
