# Generated by Django 6.0.5 on 2026-05-14 20:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrailEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(blank=True, db_index=True, null=True)),
                ('target', models.IntegerField(blank=True, db_index=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('reverse_cost', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('surface', models.CharField(blank=True, db_index=True, max_length=100)),
                ('highway', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tracktype', models.CharField(blank=True, max_length=100)),
                ('sac_scale', models.CharField(blank=True, max_length=100)),
                ('mtb_scale', models.CharField(blank=True, max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'verbose_name': 'Tramo de Aventura',
                'verbose_name_plural': 'Tramos de Aventura',
                'db_table': 'adventure_trails',
            },
        ),
    ]
