# Generated by Django 6.0.5 on 2026-05-15 21:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_fountain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('profile', models.CharField(max_length=50)),
                ('waypoints', models.JSONField(help_text='Array de coordenadas [lng, lat] para permitir edición posterior')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(help_text='La línea trazada por PgRouting', srid=4326)),
                ('distance_meters', models.FloatField()),
                ('elevation_gain', models.FloatField()),
                ('elevation_loss', models.FloatField()),
                ('surface_stats', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta Guardada',
                'verbose_name_plural': 'Rutas Guardadas',
                'db_table': 'adventure_routes',
                'ordering': ['-created_at'],
            },
        ),
    ]
