# Generated by Django 6.0.5 on 2026-05-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_inteldrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='location_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
