# Generated by Django 6.0.4 on 2026-04-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pintxos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='embedding',
        ),
    ]
