# Generated by Django 6.0.4 on 2026-04-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintxos', '0002_remove_dish_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishrating',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
