# Generated by Django 6.0.5 on 2026-05-10 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pintxos', '0005_add_dish_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='Verified owner. Set when a RestaurantClaim is approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_pintxos_venues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RestaurantClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=16)),
                ('method', models.CharField(choices=[('phone', 'Phone call'), ('email', 'Domain email'), ('document', 'Document upload'), ('other', 'Other')], default='phone', max_length=16)),
                ('evidence', models.TextField(blank=True, help_text='Free-text proof: role, contact details, supporting info.')),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes left by the reviewer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pintxos_claims', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='pintxos.restaurant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pintxos_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='pintxos_res_status_f0af88_idx')],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'claimant'), name='uniq_restaurant_claimant')],
            },
        ),
    ]
